#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-wikitext-project
Version  : 1.3
Release  : 2
URL      : https://github.com/fusesource/wikitext/archive/wikitext-project-1.3.tar.gz
Source0  : https://github.com/fusesource/wikitext/archive/wikitext-project-1.3.tar.gz
Source1  : https://repo.maven.apache.org/maven2/com/datastax/wikitext/wikitext-core-ant/1.3/wikitext-core-ant-1.3.jar
Source2  : https://repo.maven.apache.org/maven2/com/datastax/wikitext/wikitext-core-ant/1.3/wikitext-core-ant-1.3.pom
Source3  : https://repo.maven.apache.org/maven2/org/fusesource/wikitext/textile-core/1.3/textile-core-1.3.jar
Source4  : https://repo.maven.apache.org/maven2/org/fusesource/wikitext/textile-core/1.3/textile-core-1.3.pom
Source5  : https://repo.maven.apache.org/maven2/org/fusesource/wikitext/wikitext-core/1.3/wikitext-core-1.3.jar
Source6  : https://repo.maven.apache.org/maven2/org/fusesource/wikitext/wikitext-core/1.3/wikitext-core-1.3.pom
Source7  : https://repo.maven.apache.org/maven2/org/fusesource/wikitext/wikitext-project/1.3/wikitext-project-1.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 EPL-1.0
Requires: mvn-wikitext-project-data = %{version}-%{release}
Requires: mvn-wikitext-project-license = %{version}-%{release}

%description
WikiText Library
================
This is a fork of the eclipse Mylyn wikitext library so that it get
independently released from the eclipse project and pushed in the
maven central repo.

%package data
Summary: data components for the mvn-wikitext-project package.
Group: Data

%description data
data components for the mvn-wikitext-project package.


%package license
Summary: license components for the mvn-wikitext-project package.
Group: Default

%description license
license components for the mvn-wikitext-project package.


%prep
%setup -q -n wikitext-wikitext-project-1.3

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-wikitext-project
cp license.html %{buildroot}/usr/share/package-licenses/mvn-wikitext-project/license.html
cp org.eclipse.mylyn.wikitext-feature/license.html %{buildroot}/usr/share/package-licenses/mvn-wikitext-project/org.eclipse.mylyn.wikitext-feature_license.html
cp org.eclipse.mylyn.wikitext.core/about_files/LICENSE %{buildroot}/usr/share/package-licenses/mvn-wikitext-project/org.eclipse.mylyn.wikitext.core_about_files_LICENSE
cp org.eclipse.mylyn.wikitext.core/about_files/NOTICE %{buildroot}/usr/share/package-licenses/mvn-wikitext-project/org.eclipse.mylyn.wikitext.core_about_files_NOTICE
cp org.eclipse.mylyn.wikitext.sdk-feature/license.html %{buildroot}/usr/share/package-licenses/mvn-wikitext-project/org.eclipse.mylyn.wikitext.sdk-feature_license.html
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/datastax/wikitext/wikitext-core-ant/1.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/datastax/wikitext/wikitext-core-ant/1.3/wikitext-core-ant-1.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/datastax/wikitext/wikitext-core-ant/1.3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/datastax/wikitext/wikitext-core-ant/1.3/wikitext-core-ant-1.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/fusesource/wikitext/textile-core/1.3
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/fusesource/wikitext/textile-core/1.3/textile-core-1.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/fusesource/wikitext/textile-core/1.3
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/fusesource/wikitext/textile-core/1.3/textile-core-1.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/fusesource/wikitext/wikitext-core/1.3
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/fusesource/wikitext/wikitext-core/1.3/wikitext-core-1.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/fusesource/wikitext/wikitext-core/1.3
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/fusesource/wikitext/wikitext-core/1.3/wikitext-core-1.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/fusesource/wikitext/wikitext-project/1.3
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/fusesource/wikitext/wikitext-project/1.3/wikitext-project-1.3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/datastax/wikitext/wikitext-core-ant/1.3/wikitext-core-ant-1.3.jar
/usr/share/java/.m2/repository/com/datastax/wikitext/wikitext-core-ant/1.3/wikitext-core-ant-1.3.pom
/usr/share/java/.m2/repository/org/fusesource/wikitext/textile-core/1.3/textile-core-1.3.jar
/usr/share/java/.m2/repository/org/fusesource/wikitext/textile-core/1.3/textile-core-1.3.pom
/usr/share/java/.m2/repository/org/fusesource/wikitext/wikitext-core/1.3/wikitext-core-1.3.jar
/usr/share/java/.m2/repository/org/fusesource/wikitext/wikitext-core/1.3/wikitext-core-1.3.pom
/usr/share/java/.m2/repository/org/fusesource/wikitext/wikitext-project/1.3/wikitext-project-1.3.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-wikitext-project/license.html
/usr/share/package-licenses/mvn-wikitext-project/org.eclipse.mylyn.wikitext-feature_license.html
/usr/share/package-licenses/mvn-wikitext-project/org.eclipse.mylyn.wikitext.core_about_files_LICENSE
/usr/share/package-licenses/mvn-wikitext-project/org.eclipse.mylyn.wikitext.core_about_files_NOTICE
/usr/share/package-licenses/mvn-wikitext-project/org.eclipse.mylyn.wikitext.sdk-feature_license.html
